// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

import (
	"patito/semantic"
)

//line parser/parser.y:9
type yySymType struct {
	yys int
	lit string
	typ semantic.Type
	ids []string
}

const PROGRAMA = 57346
const VARS = 57347
const INICIO = 57348
const FIN = 57349
const ENTERO = 57350
const FLOTANTE = 57351
const NULA = 57352
const SI = 57353
const SINO = 57354
const MIENTRAS = 57355
const HAZ = 57356
const ESCRIBE = 57357
const ID = 57358
const CTE_ENT = 57359
const CTE_FLOT = 57360
const LETRERO = 57361
const ASIGNA = 57362
const MAS = 57363
const MENOS = 57364
const MULT = 57365
const DIVIDE = 57366
const MAYOR = 57367
const MENOR = 57368
const DIF = 57369
const IGUAL = 57370
const PUNTOCOMA = 57371
const DOSPUNTOS = 57372
const COMA = 57373
const PAR_IZQ = 57374
const PAR_DER = 57375
const LLAVE_IZQ = 57376
const LLAVE_DER = 57377
const UPLUS = 57378
const UMINUS = 57379

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PROGRAMA",
	"VARS",
	"INICIO",
	"FIN",
	"ENTERO",
	"FLOTANTE",
	"NULA",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"ID",
	"CTE_ENT",
	"CTE_FLOT",
	"LETRERO",
	"ASIGNA",
	"MAS",
	"MENOS",
	"MULT",
	"DIVIDE",
	"MAYOR",
	"MENOR",
	"DIF",
	"IGUAL",
	"PUNTOCOMA",
	"DOSPUNTOS",
	"COMA",
	"PAR_IZQ",
	"PAR_DER",
	"LLAVE_IZQ",
	"LLAVE_DER",
	"UPLUS",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:304

func Parse(l yyLexer) int {
	return yyParse(l)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 146

var yyAct = [...]uint8{
	120, 11, 23, 6, 95, 90, 71, 57, 55, 125,
	43, 56, 72, 61, 64, 65, 73, 24, 59, 60,
	97, 107, 26, 94, 93, 61, 64, 65, 92, 58,
	59, 60, 89, 82, 83, 74, 46, 78, 79, 80,
	81, 58, 47, 50, 63, 49, 48, 40, 47, 121,
	96, 91, 22, 29, 131, 75, 20, 76, 130, 54,
	67, 68, 69, 129, 127, 111, 77, 87, 88, 34,
	45, 86, 41, 5, 21, 34, 126, 98, 84, 85,
	82, 83, 52, 27, 44, 19, 16, 99, 100, 101,
	102, 4, 105, 106, 103, 104, 117, 123, 13, 14,
	12, 113, 42, 112, 108, 37, 28, 38, 17, 39,
	36, 8, 116, 7, 115, 3, 119, 118, 13, 14,
	124, 18, 70, 66, 110, 122, 128, 109, 35, 33,
	32, 31, 30, 132, 134, 133, 114, 51, 25, 9,
	53, 2, 1, 15, 62, 10,
}

var yyPact = [...]int16{
	111, -1000, -1000, 75, 44, 108, 90, 70, 102, 90,
	69, -1000, -1000, -1000, -1000, 26, 21, -17, -1000, -1000,
	110, -1000, 67, 99, 94, 15, 43, 21, -1000, -25,
	94, -1000, -1000, -1000, 41, -1000, 16, 14, 13, 11,
	66, -1000, -1000, -1000, -1000, -1000, 9, 9, 9, 9,
	-3, 2, 25, 108, 37, 12, 55, -1000, 9, 9,
	9, 10, -1000, -1000, -1000, -1000, -1, 20, -5, -9,
	-10, 19, -1000, -1000, -14, 110, -1000, -1000, 9, 9,
	9, 9, 9, 9, 9, 9, -12, -1000, -1000, -1000,
	-1000, 9, -1000, -1000, 36, -1000, -3, 108, -1000, 59,
	59, 59, 59, 55, 55, -1000, -1000, -1000, 20, -17,
	82, -1000, 19, -17, 18, -1000, 85, -17, -1000, -26,
	-1000, 60, 35, -17, 34, 29, 24, -1000, -1000, -1000,
	-1000, 110, -1000, 18, -1000,
}

var yyPgo = [...]uint8{
	0, 1, 145, 12, 8, 11, 7, 144, 143, 74,
	142, 141, 3, 111, 2, 140, 139, 138, 137, 136,
	0, 135, 53, 132, 131, 130, 129, 44, 128, 127,
	125, 124, 123, 5, 122, 6, 4,
}

var yyR1 = [...]int8{
	0, 10, 11, 15, 12, 12, 8, 9, 9, 1,
	1, 13, 13, 17, 16, 2, 2, 19, 18, 18,
	21, 20, 20, 14, 22, 22, 23, 23, 23, 23,
	23, 24, 29, 25, 30, 30, 31, 26, 27, 32,
	32, 33, 33, 28, 34, 36, 36, 35, 35, 3,
	3, 3, 3, 3, 4, 4, 4, 5, 5, 5,
	6, 6, 6, 6, 6, 6, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 8, 0, 7, 0, 2, 3, 0, 1,
	1, 2, 0, 0, 11, 1, 1, 0, 5, 0,
	0, 6, 0, 3, 2, 0, 1, 1, 1, 2,
	1, 4, 0, 8, 2, 0, 0, 8, 4, 2,
	0, 3, 0, 5, 2, 3, 0, 1, 1, 1,
	3, 3, 3, 3, 3, 3, 1, 3, 3, 1,
	3, 2, 2, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -10, -11, 4, 16, 29, -12, 5, -13, -16,
	-2, -1, 10, 8, 9, -8, 16, 6, -13, 16,
	30, -9, 31, -14, 34, -17, -1, 16, 7, -22,
	-23, -24, -25, -26, -27, -28, 16, 11, 13, 15,
	32, 29, -9, 35, -22, 29, 20, 32, 32, 32,
	32, -18, 16, -15, -3, -4, -5, -6, 32, 21,
	22, 16, -7, -27, 17, 18, -32, -3, -3, -3,
	-34, -35, -3, 19, 33, 30, -12, 29, 25, 26,
	27, 28, 21, 22, 23, 24, -3, -6, -6, 33,
	-33, 31, 33, 33, 33, -36, 31, 34, -1, -4,
	-4, -4, -4, -5, -5, -6, -6, 33, -3, -29,
	-31, 29, -35, -12, -19, -33, -14, 14, -36, -14,
	-20, 31, -30, 12, -14, 35, 16, 29, -14, 29,
	29, 30, -1, -21, -20,
}

var yyDef = [...]int8{
	0, -2, 1, 0, 0, 5, 12, 0, 0, 12,
	0, 15, 16, 9, 10, 0, 8, 0, 11, 13,
	0, 6, 0, 0, 25, 0, 0, 8, 2, 0,
	25, 26, 27, 28, 0, 30, 0, 0, 0, 0,
	19, 3, 7, 23, 24, 29, 0, 40, 0, 0,
	0, 0, 0, 5, 0, 49, 56, 59, 0, 0,
	0, 63, 64, 65, 66, 67, 0, 42, 0, 0,
	0, 46, 47, 48, 0, 0, 4, 31, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 61, 62, 38,
	39, 0, 32, 36, 0, 44, 0, 5, 17, 50,
	51, 52, 53, 54, 55, 57, 58, 60, 42, 0,
	0, 43, 46, 0, 22, 41, 35, 0, 45, 0,
	18, 0, 0, 0, 0, 0, 0, 33, 34, 37,
	14, 0, 20, 22, 21,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:55
		{
			yylex.(*PatitoLexer).Sem.AddVars(yyDollar[2].ids, yyDollar[4].typ)
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:64
		{
			yyVAL.ids = append([]string{yyDollar[1].lit}, yyDollar[2].ids...)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:71
		{
			yyVAL.ids = append([]string{yyDollar[2].lit}, yyDollar[3].ids...)
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:75
		{
			yyVAL.ids = []string{}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:81
		{
			yyVAL.typ = semantic.TypeEntero
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:85
		{
			yyVAL.typ = semantic.TypeFlotante
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:97
		{
			yylex.(*PatitoLexer).Sem.StartFunction(yyDollar[2].lit, yyDollar[1].typ)
		}
	case 14:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser/parser.y:101
		{
			yylex.(*PatitoLexer).Sem.EndFunction()
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:108
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:112
		{
			yyVAL.typ = semantic.TypeNula
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:119
		{
			yylex.(*PatitoLexer).Sem.AddVar(yyDollar[1].lit, yyDollar[3].typ)
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:128
		{
			yylex.(*PatitoLexer).Sem.AddVar(yyDollar[2].lit, yyDollar[4].typ)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:154
		{
			yylex.(*PatitoLexer).Sem.CheckAssignment(yyDollar[1].lit, yyDollar[3].typ)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:161
		{
			yylex.(*PatitoLexer).Sem.CheckCondition(yyDollar[3].typ)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:174
		{
			yylex.(*PatitoLexer).Sem.CheckCondition(yyDollar[3].typ)
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:214
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:218
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpMayor, yyDollar[3].typ)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:222
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpMenor, yyDollar[3].typ)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:226
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpDif, yyDollar[3].typ)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:230
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpIgual, yyDollar[3].typ)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:237
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpSuma, yyDollar[3].typ)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:241
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpResta, yyDollar[3].typ)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:245
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:253
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpMult, yyDollar[3].typ)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:257
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.CheckOperation(yyDollar[1].typ, semantic.OpDiv, yyDollar[3].typ)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:261
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:268
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:272
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:276
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:280
		{
			yyVAL.typ = yylex.(*PatitoLexer).Sem.GetVarType(yyDollar[1].lit)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:284
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:288
		{
			yyVAL.typ = semantic.TypeNula
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:295
		{
			yyVAL.typ = semantic.TypeEntero
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:299
		{
			yyVAL.typ = semantic.TypeFlotante
		}
	}
	goto yystack /* stack new state and value */
}
