// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

import (
	"patito/semantic"
)

//line parser/parser.y:9
type yySymType struct {
	yys int
	lit string
	typ semantic.Type
	ids []string
}

const PROGRAMA = 57346
const VARS = 57347
const INICIO = 57348
const FIN = 57349
const ENTERO = 57350
const FLOTANTE = 57351
const NULA = 57352
const SI = 57353
const SINO = 57354
const MIENTRAS = 57355
const HAZ = 57356
const ESCRIBE = 57357
const ID = 57358
const CTE_ENT = 57359
const CTE_FLOT = 57360
const LETRERO = 57361
const ASIGNA = 57362
const MAS = 57363
const MENOS = 57364
const MULT = 57365
const DIVIDE = 57366
const MAYOR = 57367
const MENOR = 57368
const DIF = 57369
const IGUAL = 57370
const PUNTOCOMA = 57371
const DOSPUNTOS = 57372
const COMA = 57373
const PAR_IZQ = 57374
const PAR_DER = 57375
const LLAVE_IZQ = 57376
const LLAVE_DER = 57377
const UPLUS = 57378
const UMINUS = 57379

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PROGRAMA",
	"VARS",
	"INICIO",
	"FIN",
	"ENTERO",
	"FLOTANTE",
	"NULA",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"ID",
	"CTE_ENT",
	"CTE_FLOT",
	"LETRERO",
	"ASIGNA",
	"MAS",
	"MENOS",
	"MULT",
	"DIVIDE",
	"MAYOR",
	"MENOR",
	"DIF",
	"IGUAL",
	"PUNTOCOMA",
	"DOSPUNTOS",
	"COMA",
	"PAR_IZQ",
	"PAR_DER",
	"LLAVE_IZQ",
	"LLAVE_DER",
	"UPLUS",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:412

func Parse(l yyLexer) int {
	return yyParse(l)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 66,
	32, 42,
	-2, 78,
}

const yyPrivate = 57344

const yyLast = 160

var yyAct = [...]uint8{
	117, 28, 12, 76, 127, 97, 61, 62, 75, 68,
	7, 66, 69, 70, 77, 60, 64, 65, 34, 132,
	66, 69, 70, 48, 26, 64, 65, 63, 29, 73,
	78, 113, 110, 109, 96, 94, 63, 85, 86, 39,
	56, 81, 82, 83, 84, 39, 71, 55, 147, 53,
	30, 118, 128, 98, 49, 59, 23, 72, 58, 139,
	79, 57, 21, 141, 138, 114, 80, 89, 50, 31,
	5, 22, 90, 91, 51, 93, 133, 95, 87, 88,
	85, 86, 42, 46, 43, 27, 44, 41, 20, 99,
	17, 4, 137, 136, 14, 15, 13, 9, 33, 32,
	8, 116, 14, 15, 18, 3, 108, 115, 19, 107,
	106, 105, 123, 124, 129, 125, 126, 119, 120, 121,
	122, 131, 104, 103, 102, 101, 74, 140, 111, 92,
	52, 130, 134, 54, 142, 135, 112, 40, 38, 143,
	37, 36, 144, 35, 146, 145, 148, 100, 45, 149,
	25, 10, 47, 24, 6, 2, 1, 16, 67, 11,
}

var yyPact = [...]int16{
	101, -1000, -1000, 75, 41, -1000, 95, 86, 74, 98,
	86, 72, -1000, -1000, -1000, -1000, 32, 25, -1000, -1000,
	-1000, 94, -1000, 69, -6, 18, 40, 25, 91, 71,
	67, -1000, -1000, -1000, -12, 71, -1000, -1000, -1000, 39,
	-1000, 54, 17, -1000, 15, 7, 31, 95, -1000, -1000,
	-1000, 4, 14, 4, -3, -5, -4, 94, -1000, 37,
	16, 55, -1000, 4, 4, 4, -1000, -1000, -1000, -1000,
	-1000, 4, 2, 4, 1, 22, -1000, -1000, 95, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 0,
	-1000, -1000, -1, -1000, -1000, -2, 36, -1000, -5, -6,
	20, 4, 4, 4, 4, 4, 4, 4, 4, -1000,
	-1000, 21, -6, -1000, -1000, 22, -16, -1000, 60, 59,
	59, 59, 59, 55, 55, -1000, -1000, -1000, 4, 81,
	78, -1000, 35, 29, -1000, 34, -1000, -6, -1000, 94,
	21, -1000, -6, 19, -1000, -1000, -1000, -1000, 20, -1000,
}

var yyPgo = [...]uint8{
	0, 2, 159, 3, 15, 6, 7, 158, 157, 71,
	156, 155, 154, 10, 97, 153, 1, 152, 151, 150,
	148, 147, 0, 146, 18, 143, 141, 140, 138, 9,
	137, 136, 135, 134, 133, 131, 130, 129, 128, 4,
	127, 126, 8, 5, 125, 124, 123, 122, 111, 110,
	109, 106,
}

var yyR1 = [...]int8{
	0, 10, 12, 15, 11, 17, 13, 13, 8, 9,
	9, 1, 1, 14, 14, 19, 18, 2, 2, 21,
	20, 20, 23, 22, 22, 16, 24, 24, 25, 25,
	25, 25, 25, 26, 31, 27, 33, 32, 32, 34,
	35, 28, 36, 29, 38, 37, 37, 40, 39, 39,
	30, 41, 43, 43, 42, 42, 3, 44, 3, 45,
	3, 46, 3, 47, 3, 48, 4, 49, 4, 4,
	50, 5, 51, 5, 5, 6, 6, 6, 6, 6,
	6, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 0, 0, 10, 0, 7, 0, 2, 3,
	0, 1, 1, 2, 0, 0, 11, 1, 1, 0,
	5, 0, 0, 6, 0, 3, 2, 0, 1, 1,
	1, 2, 1, 4, 0, 8, 0, 3, 0, 0,
	0, 9, 0, 5, 0, 3, 0, 0, 4, 0,
	5, 2, 3, 0, 1, 1, 1, 0, 4, 0,
	4, 0, 4, 0, 4, 0, 4, 0, 4, 1,
	0, 4, 0, 4, 1, 3, 2, 2, 1, 1,
	1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -10, -11, 4, 16, 29, -12, -13, 5, -14,
	-18, -2, -1, 10, 8, 9, -8, 16, 6, -14,
	16, 30, -9, 31, -15, -19, -1, 16, -16, 34,
	32, 29, -9, 7, -24, -25, -26, -27, -28, -29,
	-30, 16, 11, 13, 15, -20, 16, -17, 35, -24,
	29, 20, -36, 32, -34, 32, 33, 30, -13, -3,
	-4, -5, -6, 32, 21, 22, 16, -7, -29, 17,
	18, 32, -3, 32, -41, -42, -3, 19, 34, -1,
	29, 25, 26, 27, 28, 21, 22, 23, 24, -3,
	-6, -6, -37, -3, 33, -3, 33, -43, 31, -13,
	-21, -44, -45, -46, -47, -48, -49, -50, -51, 33,
	33, -38, -31, 33, 29, -42, -16, -22, 31, -4,
	-4, -4, -4, -5, -5, -6, -6, -39, 31, -16,
	-35, -43, 35, 16, -3, -32, 12, 14, 29, 30,
	-40, 29, -33, -16, -1, -39, -16, 29, -23, -22,
}

var yyDef = [...]int8{
	0, -2, 1, 0, 0, 2, 7, 14, 0, 0,
	14, 0, 17, 18, 11, 12, 0, 10, 3, 13,
	15, 0, 8, 0, 0, 0, 0, 10, 0, 27,
	21, 5, 9, 4, 0, 27, 28, 29, 30, 0,
	32, 42, 0, 39, 0, 0, 0, 7, 25, 26,
	31, 0, 0, 0, 0, 0, 0, 0, 6, 0,
	56, 69, 74, 0, 0, 0, -2, 79, 80, 81,
	82, 46, 0, 0, 0, 53, 54, 55, 7, 19,
	33, 57, 59, 61, 63, 65, 67, 70, 72, 0,
	76, 77, 0, 44, 34, 0, 0, 51, 0, 0,
	24, 0, 0, 0, 0, 0, 0, 0, 0, 75,
	43, 49, 0, 40, 50, 53, 0, 20, 0, 58,
	60, 62, 64, 66, 68, 71, 73, 45, 0, 38,
	0, 52, 0, 0, 47, 0, 36, 0, 16, 0,
	49, 35, 0, 0, 22, 48, 37, 41, 24, 23,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:51
		{
			yylex.(*PatitoLexer).Gen.GenerateMainGoto()
		}
	case 3:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:55
		{
			yylex.(*PatitoLexer).Gen.FillMainGoto()
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:63
		{
			yylex.(*PatitoLexer).Sem.AddVars(yyDollar[2].ids, yyDollar[4].typ)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:72
		{
			yyVAL.ids = append([]string{yyDollar[1].lit}, yyDollar[2].ids...)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:79
		{
			yyVAL.ids = append([]string{yyDollar[2].lit}, yyDollar[3].ids...)
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:83
		{
			yyVAL.ids = []string{}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:89
		{
			yyVAL.typ = semantic.TypeEntero
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:93
		{
			yyVAL.typ = semantic.TypeFlotante
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:105
		{
			yylex.(*PatitoLexer).Sem.StartFunction(yyDollar[2].lit, yyDollar[1].typ)
			yylex.(*PatitoLexer).Sem.SetFunctionStart(yyDollar[2].lit, yylex.(*PatitoLexer).Gen.NextQuad())
		}
	case 16:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser/parser.y:110
		{
			yylex.(*PatitoLexer).Gen.GenerateEndFunc()
			yylex.(*PatitoLexer).Sem.EndFunction()
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:118
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:122
		{
			yyVAL.typ = semantic.TypeNula
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:129
		{
			yylex.(*PatitoLexer).Sem.AddVar(yyDollar[1].lit, yyDollar[3].typ)
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:138
		{
			yylex.(*PatitoLexer).Sem.AddVar(yyDollar[2].lit, yyDollar[4].typ)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:164
		{
			destAddr, varType := yylex.(*PatitoLexer).Sem.GetVarAddressAndType(yyDollar[1].lit)

			if varType != semantic.TypeError && yyDollar[3].typ != semantic.TypeError {
				yylex.(*PatitoLexer).Gen.GenerateAssignment(destAddr, varType)
			}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:175
		{
			yylex.(*PatitoLexer).Gen.StartIf()
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:183
		{
			yylex.(*PatitoLexer).Gen.ElseIf()
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:187
		{
			yylex.(*PatitoLexer).Gen.EndIfElse()
		}
	case 38:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:191
		{
			yylex.(*PatitoLexer).Gen.EndIf()
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:198
		{
			yylex.(*PatitoLexer).Gen.StartWhile()
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:202
		{
			yylex.(*PatitoLexer).Gen.WhileCondition()
		}
	case 41:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:206
		{
			yylex.(*PatitoLexer).Gen.EndWhile()
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:213
		{
			yylex.(*PatitoLexer).Sem.StartCall(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.GenerateERA(yyDollar[1].lit)
		}
	case 43:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:218
		{
			startQuad := yylex.(*PatitoLexer).Sem.EndCall(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.GenerateGOSUB(yyDollar[1].lit, startQuad)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:226
		{
			param, ok := yylex.(*PatitoLexer).Sem.GetCurrentParam()
			if ok {
				yylex.(*PatitoLexer).Gen.GenerateParam(param.Type, param.Address)
			}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:238
		{
			param, ok := yylex.(*PatitoLexer).Sem.GetCurrentParam()
			if ok {
				yylex.(*PatitoLexer).Gen.GenerateParam(param.Type, param.Address)
			}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:263
		{
			value := yylex.(*PatitoLexer).Gen.PopOperandForPrint()
			yylex.(*PatitoLexer).Gen.GeneratePrint(value)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:268
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeString)
			yylex.(*PatitoLexer).Gen.GeneratePrint(addr)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:276
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:280
		{
			yylex.(*PatitoLexer).Gen.PushOperator(">")
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:284
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:289
		{
			yylex.(*PatitoLexer).Gen.PushOperator("<")
		}
	case 60:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:293
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:298
		{
			yylex.(*PatitoLexer).Gen.PushOperator("!=")
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:302
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:307
		{
			yylex.(*PatitoLexer).Gen.PushOperator("==")
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:311
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:319
		{
			yylex.(*PatitoLexer).Gen.PushOperator("+")
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:323
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:328
		{
			yylex.(*PatitoLexer).Gen.PushOperator("-")
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:332
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:337
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:345
		{
			yylex.(*PatitoLexer).Gen.PushOperator("*")
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:349
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:354
		{
			yylex.(*PatitoLexer).Gen.PushOperator("/")
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:358
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:363
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:370
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:374
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:378
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:382
		{
			addr, t := yylex.(*PatitoLexer).Sem.GetVarAddressAndType(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, t)
			yyVAL.typ = t
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:388
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:392
		{
			yyVAL.typ = semantic.TypeNula
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:399
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeEntero)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeEntero)
			yyVAL.typ = semantic.TypeEntero
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:405
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeFlotante)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeFlotante)
			yyVAL.typ = semantic.TypeFlotante
		}
	}
	goto yystack /* stack new state and value */
}
