// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

//line parser/parser.y:5
type yySymType struct {
	yys int
	lit string
}

const PROGRAMA = 57346
const VARS = 57347
const INICIO = 57348
const FIN = 57349
const ENTERO = 57350
const FLOTANTE = 57351
const NULA = 57352
const SI = 57353
const SINO = 57354
const MIENTRAS = 57355
const HAZ = 57356
const ESCRIBE = 57357
const ID = 57358
const CTE_ENT = 57359
const CTE_FLOT = 57360
const LETRERO = 57361
const ASIGNA = 57362
const MAS = 57363
const MENOS = 57364
const MULT = 57365
const DIVIDE = 57366
const MAYOR = 57367
const MENOR = 57368
const DIF = 57369
const IGUAL = 57370
const PUNTOCOMA = 57371
const DOSPUNTOS = 57372
const COMA = 57373
const PAR_IZQ = 57374
const PAR_DER = 57375
const LLAVE_IZQ = 57376
const LLAVE_DER = 57377
const UPLUS = 57378
const UMINUS = 57379

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PROGRAMA",
	"VARS",
	"INICIO",
	"FIN",
	"ENTERO",
	"FLOTANTE",
	"NULA",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"ID",
	"CTE_ENT",
	"CTE_FLOT",
	"LETRERO",
	"ASIGNA",
	"MAS",
	"MENOS",
	"MULT",
	"DIVIDE",
	"MAYOR",
	"MENOR",
	"DIF",
	"IGUAL",
	"PUNTOCOMA",
	"DOSPUNTOS",
	"COMA",
	"PAR_IZQ",
	"PAR_DER",
	"LLAVE_IZQ",
	"LLAVE_DER",
	"UPLUS",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:191

func Parse(l yyLexer) int {
	return yyParse(l)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 138

var yyAct = [...]int8{
	99, 11, 23, 96, 72, 91, 58, 57, 6, 119,
	73, 56, 62, 65, 66, 74, 44, 60, 61, 62,
	65, 66, 26, 24, 60, 61, 75, 106, 59, 116,
	95, 94, 93, 90, 52, 59, 79, 80, 47, 48,
	81, 82, 83, 84, 51, 50, 49, 64, 25, 29,
	48, 54, 100, 97, 92, 76, 22, 120, 55, 68,
	69, 70, 53, 20, 124, 123, 121, 88, 89, 110,
	87, 77, 34, 46, 42, 5, 21, 113, 34, 41,
	45, 85, 86, 27, 98, 79, 80, 102, 103, 19,
	101, 16, 104, 105, 4, 37, 108, 38, 17, 39,
	36, 112, 111, 107, 43, 109, 13, 14, 12, 13,
	14, 8, 117, 114, 28, 118, 7, 3, 63, 122,
	78, 18, 125, 71, 67, 115, 126, 35, 33, 32,
	31, 30, 40, 10, 9, 15, 2, 1,
}

var yyPact = [...]int16{
	113, -1000, -1000, 78, 46, 111, 98, 75, 92, 98,
	73, -1000, -1000, -1000, -1000, 33, 25, -11, -1000, 16,
	101, -1000, 67, 107, 84, 63, 45, 25, -1000, -19,
	84, -1000, -1000, -1000, 44, -1000, 18, 14, 13, 12,
	1, 32, 111, -1000, -1000, -1000, -1000, 3, 3, 3,
	3, -4, -8, 101, -1000, 42, 15, 58, -1000, 3,
	3, 3, 7, -1000, -1000, -1000, -1000, 0, 23, -1,
	-2, -3, 22, -1000, -1000, 111, 21, -1000, 3, 3,
	3, -1000, -1000, -1000, -1000, 3, 3, -6, -1000, -1000,
	-1000, -1000, 3, -11, 91, 40, -1000, -4, -11, -1000,
	61, 64, 58, 58, -1000, -1000, -1000, 23, 17, -11,
	-1000, 22, -26, 27, -1000, 37, -11, 36, -1000, 35,
	101, -1000, -1000, -1000, -1000, 21, -1000,
}

var yyPgo = [...]uint8{
	0, 137, 136, 8, 111, 2, 135, 1, 76, 134,
	133, 132, 0, 49, 131, 130, 129, 128, 47, 127,
	10, 125, 124, 5, 123, 4, 3, 11, 120, 7,
	6, 118,
}

var yyR1 = [...]int8{
	0, 1, 2, 3, 3, 6, 8, 8, 7, 7,
	4, 4, 9, 10, 10, 11, 11, 12, 12, 5,
	13, 13, 14, 14, 14, 14, 14, 15, 16, 21,
	21, 17, 18, 22, 22, 23, 23, 19, 24, 26,
	26, 25, 25, 20, 20, 28, 28, 28, 28, 27,
	27, 27, 29, 29, 29, 30, 30, 30, 30, 30,
	30, 31, 31,
}

var yyR2 = [...]int8{
	0, 1, 8, 6, 0, 2, 3, 0, 1, 1,
	2, 0, 10, 1, 1, 4, 0, 5, 0, 3,
	2, 0, 1, 1, 1, 2, 1, 4, 7, 2,
	0, 7, 4, 2, 0, 3, 0, 5, 2, 3,
	0, 1, 1, 1, 3, 1, 1, 1, 1, 3,
	3, 1, 3, 3, 1, 3, 2, 2, 1, 1,
	1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, 4, 16, 29, -3, 5, -4, -9,
	-10, -7, 10, 8, 9, -6, 16, 6, -4, 16,
	30, -8, 31, -5, 34, 32, -7, 16, 7, -13,
	-14, -15, -16, -17, -18, -19, 16, 11, 13, 15,
	-11, 16, 29, -8, 35, -13, 29, 20, 32, 32,
	32, 32, 33, 30, -3, -20, -27, -29, -30, 32,
	21, 22, 16, -31, -18, 17, 18, -22, -20, -20,
	-20, -24, -25, -20, 19, 34, -7, 29, -28, 21,
	22, 25, 26, 27, 28, 23, 24, -20, -30, -30,
	33, -23, 31, 33, 33, 33, -26, 31, -3, -12,
	31, -27, -29, -29, -30, -30, 33, -20, -5, 14,
	29, -25, -5, 16, -23, -21, 12, -5, -26, 35,
	30, 29, -5, 29, 29, -7, -12,
}

var yyDef = [...]int8{
	0, -2, 1, 0, 0, 4, 11, 0, 0, 11,
	0, 13, 14, 8, 9, 0, 7, 0, 10, 0,
	0, 5, 0, 0, 21, 16, 0, 7, 2, 0,
	21, 22, 23, 24, 0, 26, 0, 0, 0, 0,
	0, 0, 4, 6, 19, 20, 25, 0, 34, 0,
	0, 0, 0, 0, 3, 0, 43, 51, 54, 0,
	0, 0, 58, 59, 60, 61, 62, 0, 36, 0,
	0, 0, 40, 41, 42, 4, 18, 27, 0, 0,
	0, 45, 46, 47, 48, 0, 0, 0, 56, 57,
	32, 33, 0, 0, 0, 0, 38, 0, 0, 15,
	0, 44, 49, 50, 52, 53, 55, 36, 30, 0,
	37, 40, 0, 0, 35, 0, 0, 0, 39, 0,
	0, 28, 29, 31, 12, 18, 17,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	}
	goto yystack /* stack new state and value */
}
