// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:1

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

import (
	"patito/semantic"
)

//line parser/parser.y:9
type yySymType struct {
	yys int
	lit string
	typ semantic.Type
	ids []string
}

const PROGRAMA = 57346
const VARS = 57347
const INICIO = 57348
const FIN = 57349
const ENTERO = 57350
const FLOTANTE = 57351
const STRING = 57352
const BOOL = 57353
const NULA = 57354
const SI = 57355
const SINO = 57356
const MIENTRAS = 57357
const HAZ = 57358
const ESCRIBE = 57359
const ID = 57360
const CTE_ENT = 57361
const CTE_FLOT = 57362
const LETRERO = 57363
const VERDADERO = 57364
const FALSO = 57365
const ASIGNA = 57366
const MAS = 57367
const MENOS = 57368
const MULT = 57369
const DIVIDE = 57370
const MAYOR = 57371
const MENOR = 57372
const DIF = 57373
const IGUAL = 57374
const PUNTOCOMA = 57375
const DOSPUNTOS = 57376
const COMA = 57377
const PAR_IZQ = 57378
const PAR_DER = 57379
const LLAVE_IZQ = 57380
const LLAVE_DER = 57381
const RETURN = 57382
const UPLUS = 57383
const UMINUS = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PROGRAMA",
	"VARS",
	"INICIO",
	"FIN",
	"ENTERO",
	"FLOTANTE",
	"STRING",
	"BOOL",
	"NULA",
	"SI",
	"SINO",
	"MIENTRAS",
	"HAZ",
	"ESCRIBE",
	"ID",
	"CTE_ENT",
	"CTE_FLOT",
	"LETRERO",
	"VERDADERO",
	"FALSO",
	"ASIGNA",
	"MAS",
	"MENOS",
	"MULT",
	"DIVIDE",
	"MAYOR",
	"MENOR",
	"DIF",
	"IGUAL",
	"PUNTOCOMA",
	"DOSPUNTOS",
	"COMA",
	"PAR_IZQ",
	"PAR_DER",
	"LLAVE_IZQ",
	"LLAVE_DER",
	"RETURN",
	"UPLUS",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:456

func Parse(l yyLexer) int {
	return yyParse(l)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 68,
	36, 46,
	-2, 81,
}

const yyPrivate = 57344

const yyLast = 166

var yyAct = [...]uint8{
	121, 30, 81, 12, 131, 101, 63, 64, 80, 7,
	137, 143, 50, 70, 31, 62, 68, 71, 72, 75,
	73, 74, 82, 66, 67, 156, 36, 28, 117, 114,
	113, 100, 98, 58, 65, 89, 90, 144, 78, 85,
	86, 87, 88, 76, 57, 41, 158, 55, 32, 122,
	132, 41, 102, 25, 145, 59, 61, 23, 77, 60,
	155, 150, 147, 83, 51, 118, 84, 52, 93, 33,
	5, 24, 91, 92, 94, 95, 89, 90, 53, 97,
	44, 99, 45, 138, 46, 43, 48, 29, 22, 19,
	4, 142, 103, 14, 15, 16, 17, 13, 141, 9,
	35, 34, 20, 112, 8, 120, 14, 15, 16, 17,
	21, 119, 3, 111, 110, 109, 127, 128, 133, 129,
	130, 123, 124, 125, 126, 135, 108, 107, 106, 105,
	79, 146, 115, 96, 54, 139, 134, 56, 148, 140,
	116, 42, 40, 39, 149, 38, 37, 151, 157, 152,
	154, 153, 104, 136, 47, 27, 10, 49, 159, 26,
	6, 2, 1, 18, 69, 11,
}

var yyPact = [...]int16{
	108, -1000, -1000, 72, 37, -1000, 99, 85, 71, 96,
	85, 70, -1000, -1000, -1000, -1000, -1000, -1000, 23, 18,
	-1000, -1000, -1000, 98, -1000, 69, -24, 12, 36, 18,
	93, 67, 68, -1000, -1000, -1000, -27, 67, -1000, -1000,
	-1000, 34, -1000, 54, 11, -1000, 8, -4, 21, 99,
	-1000, -1000, -1000, -2, 7, -2, 2, -2, -16, 98,
	-1000, 33, 10, 45, -1000, -2, -2, -2, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -2, -5, -2, -6,
	17, -1000, 99, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -7, -1000, -1000, -8, -1000, -1000, -9,
	32, -1000, -2, -24, 14, -2, -2, -2, -2, -2,
	-2, -2, -2, -1000, -1000, 15, -24, -1000, -1000, 17,
	-30, -1000, 65, 51, 51, 51, 51, 45, 45, -1000,
	-1000, -1000, -2, 84, 75, -1000, -28, 1, 20, -1000,
	29, -1000, -24, 28, -2, 98, 15, -1000, -24, 27,
	-1000, -12, -1000, -1000, -1000, -1000, 13, 14, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 3, 165, 2, 15, 6, 7, 164, 163, 71,
	162, 161, 160, 9, 99, 159, 1, 157, 156, 155,
	154, 153, 152, 0, 148, 26, 146, 145, 143, 142,
	13, 141, 140, 139, 138, 137, 136, 134, 133, 132,
	4, 131, 130, 8, 5, 129, 128, 127, 126, 115,
	114, 113, 103,
}

var yyR1 = [...]int8{
	0, 10, 12, 15, 11, 17, 13, 13, 8, 9,
	9, 1, 1, 1, 1, 14, 14, 19, 18, 21,
	21, 2, 2, 22, 20, 20, 24, 23, 23, 16,
	25, 25, 26, 26, 26, 26, 26, 27, 32, 28,
	34, 33, 33, 35, 36, 29, 37, 30, 39, 38,
	38, 41, 40, 40, 31, 42, 44, 44, 43, 3,
	45, 3, 46, 3, 47, 3, 48, 3, 49, 4,
	50, 4, 4, 51, 5, 52, 5, 5, 6, 6,
	6, 6, 6, 6, 7, 7, 7, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 0, 0, 10, 0, 7, 0, 2, 3,
	0, 1, 1, 1, 1, 2, 0, 0, 12, 5,
	0, 1, 1, 0, 5, 0, 0, 6, 0, 3,
	2, 0, 1, 1, 1, 2, 1, 4, 0, 8,
	0, 3, 0, 0, 0, 9, 0, 5, 0, 3,
	0, 0, 4, 0, 5, 2, 3, 0, 1, 1,
	0, 4, 0, 4, 0, 4, 0, 4, 0, 4,
	0, 4, 1, 0, 4, 0, 4, 1, 3, 2,
	2, 1, 1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -10, -11, 4, 18, 33, -12, -13, 5, -14,
	-18, -2, -1, 12, 8, 9, 10, 11, -8, 18,
	6, -14, 18, 34, -9, 35, -15, -19, -1, 18,
	-16, 38, 36, 33, -9, 7, -25, -26, -27, -28,
	-29, -30, -31, 18, 13, 15, 17, -20, 18, -17,
	39, -25, 33, 24, -37, 36, -35, 36, 37, 34,
	-13, -3, -4, -5, -6, 36, 25, 26, 18, -7,
	-30, 19, 20, 22, 23, 21, 36, -3, 36, -42,
	-43, -3, 38, -1, 33, 29, 30, 31, 32, 25,
	26, 27, 28, -3, -6, -6, -38, -3, 37, -3,
	37, -44, 35, -13, -22, -45, -46, -47, -48, -49,
	-50, -51, -52, 37, 37, -39, -32, 37, 33, -43,
	-16, -23, 35, -4, -4, -4, -4, -5, -5, -6,
	-6, -40, 35, -16, -36, -44, -21, 40, 18, -3,
	-33, 14, 16, 39, 36, 34, -41, 33, -34, -16,
	33, -3, -1, -40, -16, 33, 37, -24, 33, -23,
}

var yyDef = [...]int8{
	0, -2, 1, 0, 0, 2, 7, 16, 0, 0,
	16, 0, 21, 22, 11, 12, 13, 14, 0, 10,
	3, 15, 17, 0, 8, 0, 0, 0, 0, 10,
	0, 31, 25, 5, 9, 4, 0, 31, 32, 33,
	34, 0, 36, 46, 0, 43, 0, 0, 0, 7,
	29, 30, 35, 0, 0, 0, 0, 0, 0, 0,
	6, 0, 59, 72, 77, 0, 0, 0, -2, 82,
	83, 84, 85, 86, 87, 88, 50, 0, 0, 0,
	57, 58, 7, 23, 37, 60, 62, 64, 66, 68,
	70, 73, 75, 0, 79, 80, 0, 48, 38, 0,
	0, 55, 0, 0, 28, 0, 0, 0, 0, 0,
	0, 0, 0, 78, 47, 53, 0, 44, 54, 57,
	20, 24, 0, 61, 63, 65, 67, 69, 71, 74,
	76, 49, 0, 42, 0, 56, 0, 0, 0, 51,
	0, 40, 0, 0, 0, 0, 53, 39, 0, 0,
	18, 0, 26, 52, 41, 45, 0, 28, 19, 27,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:53
		{
			yylex.(*PatitoLexer).Gen.GenerateMainGoto()
		}
	case 3:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:57
		{
			yylex.(*PatitoLexer).Gen.FillMainGoto()
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:65
		{
			yylex.(*PatitoLexer).Sem.AddVars(yyDollar[2].ids, yyDollar[4].typ)
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:74
		{
			yyVAL.ids = append([]string{yyDollar[1].lit}, yyDollar[2].ids...)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:81
		{
			yyVAL.ids = append([]string{yyDollar[2].lit}, yyDollar[3].ids...)
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:85
		{
			yyVAL.ids = []string{}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:91
		{
			yyVAL.typ = semantic.TypeEntero
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:95
		{
			yyVAL.typ = semantic.TypeFlotante
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:99
		{
			yyVAL.typ = semantic.TypeString
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:103
		{
			yyVAL.typ = semantic.TypeBool
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:115
		{
			yylex.(*PatitoLexer).Sem.StartFunction(yyDollar[2].lit, yyDollar[1].typ)
			yylex.(*PatitoLexer).Sem.SetFunctionStart(yyDollar[2].lit, yylex.(*PatitoLexer).Gen.NextQuad())
		}
	case 18:
		yyDollar = yyS[yypt-12 : yypt+1]
//line parser/parser.y:120
		{
			yylex.(*PatitoLexer).Gen.GenerateEndFunc()
			yylex.(*PatitoLexer).Sem.EndFunction()
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:128
		{
			yylex.(*PatitoLexer).Sem.CheckReturn(yyDollar[3].typ)

			returnAddr := yylex.(*PatitoLexer).Sem.GetCurrentFunctionReturnAddress()
			yylex.(*PatitoLexer).Gen.GenerateReturn(returnAddr)
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:135
		{
			yylex.(*PatitoLexer).Sem.CheckMissingReturn()
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:142
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:146
		{
			yyVAL.typ = semantic.TypeNula
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:153
		{
			yylex.(*PatitoLexer).Sem.AddParam(yyDollar[1].lit, yyDollar[3].typ)
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:162
		{
			yylex.(*PatitoLexer).Sem.AddParam(yyDollar[2].lit, yyDollar[4].typ)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:188
		{
			destAddr, varType := yylex.(*PatitoLexer).Sem.GetVarAddressAndType(yyDollar[1].lit)

			if varType != semantic.TypeError && yyDollar[3].typ != semantic.TypeError {
				yylex.(*PatitoLexer).Gen.GenerateAssignment(destAddr, varType)
			}
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:199
		{
			yylex.(*PatitoLexer).Gen.StartIf()
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:207
		{
			yylex.(*PatitoLexer).Gen.ElseIf()
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:211
		{
			yylex.(*PatitoLexer).Gen.EndIfElse()
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:215
		{
			yylex.(*PatitoLexer).Gen.EndIf()
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:222
		{
			yylex.(*PatitoLexer).Gen.StartWhile()
		}
	case 44:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:226
		{
			yylex.(*PatitoLexer).Gen.WhileCondition()
		}
	case 45:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:230
		{
			yylex.(*PatitoLexer).Gen.EndWhile()
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:237
		{
			yylex.(*PatitoLexer).Sem.StartCall(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.GenerateERA(yyDollar[1].lit)
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:242
		{
			startQuad := yylex.(*PatitoLexer).Sem.EndCall(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.GenerateGOSUB(yyDollar[1].lit, startQuad)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:250
		{
			param, ok := yylex.(*PatitoLexer).Sem.GetCurrentParam()
			if ok {
				yylex.(*PatitoLexer).Gen.GenerateParam(param.Type, param.Address)
			}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:262
		{
			param, ok := yylex.(*PatitoLexer).Sem.GetCurrentParam()
			if ok {
				yylex.(*PatitoLexer).Gen.GenerateParam(param.Type, param.Address)
			}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:287
		{
			value := yylex.(*PatitoLexer).Gen.PopOperandForPrint()
			yylex.(*PatitoLexer).Gen.GeneratePrint(value)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:295
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:299
		{
			yylex.(*PatitoLexer).Gen.PushOperator(">")
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:303
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:308
		{
			yylex.(*PatitoLexer).Gen.PushOperator("<")
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:312
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:317
		{
			yylex.(*PatitoLexer).Gen.PushOperator("!=")
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:321
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:326
		{
			yylex.(*PatitoLexer).Gen.PushOperator("==")
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:330
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:338
		{
			yylex.(*PatitoLexer).Gen.PushOperator("+")
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:342
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:347
		{
			yylex.(*PatitoLexer).Gen.PushOperator("-")
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:351
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:356
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:364
		{
			yylex.(*PatitoLexer).Gen.PushOperator("*")
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:368
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:373
		{
			yylex.(*PatitoLexer).Gen.PushOperator("/")
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:377
		{
			yylex.(*PatitoLexer).Gen.GenerateBinaryOperation()
			yyVAL.typ = yylex.(*PatitoLexer).Gen.PeekType()
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:382
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:389
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:393
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:397
		{
			yyVAL.typ = yyDollar[2].typ
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:401
		{
			addr, t := yylex.(*PatitoLexer).Sem.GetVarAddressAndType(yyDollar[1].lit)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, t)
			yyVAL.typ = t
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:407
		{
			yyVAL.typ = yyDollar[1].typ
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:411
		{
			t := yylex.(*PatitoLexer).Sem.GetLastCallReturnType()

			if t != semantic.TypeNula {
				returnAddr := yylex.(*PatitoLexer).Sem.GetLastCallReturnAddress()
				yylex.(*PatitoLexer).Gen.GenerateFunctionReturnCopy(returnAddr, t)
			}

			yyVAL.typ = t
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:425
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeEntero)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeEntero)
			yyVAL.typ = semantic.TypeEntero
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:431
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeFlotante)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeFlotante)
			yyVAL.typ = semantic.TypeFlotante
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:437
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant("verdadero", semantic.TypeBool)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeBool)
			yyVAL.typ = semantic.TypeBool
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:443
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant("falso", semantic.TypeBool)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeBool)
			yyVAL.typ = semantic.TypeBool
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:449
		{
			addr := yylex.(*PatitoLexer).Sem.AddConstant(yyDollar[1].lit, semantic.TypeString)
			yylex.(*PatitoLexer).Gen.PushOperand(addr, semantic.TypeString)
			yyVAL.typ = semantic.TypeString
		}
	}
	goto yystack /* stack new state and value */
}
